domain_path: A:\WSU\EE_234\Projects\Project3\platform3\export\platform3\sw\standalone_ps7_cortexa9_0
app_src_dir: A:\AMD\2025.2\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
