domain_path: C:\WSU\EE234\EE234Projects\Project3\platform3\export\platform3\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\AMDDesignTools\2025.2\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
